[project]
name = "fdi-pln-2603-p1"
version = "2.0"
description = "Agente negociador PLN"
authors = [{ name = "Equipo Nortenios" }]
dependencies = ["requests"]

[project.scripts]
fdi-pln-2603-p1 = "src.main:run"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["src"]

